name: Wdrozenie na Serwer

on:
  push:
    branches: [ "master" ]

jobs:
  buduj-i-wyslij:
    name: Budowanie i Wysylanie Obrazu Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Ustawienie JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Budowanie aplikacji za pomoca Mavena
        run: mvn -B package --file pom.xml -DskipTests

      - name: Logowanie do GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} # Użyto DOCKER_PASSWORD

      - name: Budowanie i wysylanie obrazu Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/adixox5/gamehub:latest

  wdrozenie:
    name: Wdrozenie na Serwer
    needs: buduj-i-wyslij
    runs-on: ubuntu-latest
    steps:
      - name: Polaczenie z serwerem i wdrozenie
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin # Użyto DOCKER_PASSWORD
            
            cd /home/${{ secrets.SSH_USER }}
            
            ENV_FILE_PATH=/home/${{ secrets.SSH_USER }}/.env
            
            sudo env $(cat $ENV_FILE_PATH | xargs) docker compose pull
            
            sudo env $(cat $ENV_FILE_PATH | xargs) docker compose up -d --force-recreate
            
            sudo docker image prune -f